# Generated by Django 6.0 on 2026-05-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stagaire', '0002_userprofile_address_userprofile_phone_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gestion_stagaire.project'),
        ),
    ]
