# Generated by Django 6.0 on 2026-05-22 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stagaire', '0004_internship_alter_userprofile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('achievements', models.TextField()),
                ('lessons_learned', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='final_reports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('mentor_notes', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_final_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='gestion_stagaire.project')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport Final',
                'verbose_name_plural': 'Rapports Finaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('work_done', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='weekly_reports/%Y/%m/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='weekly_reports/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='draft', max_length=20)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('mentor_notes', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_weekly_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='gestion_stagaire.project')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport Hebdomadaire',
                'verbose_name_plural': 'Rapports Hebdomadaires',
                'ordering': ['-week_start_date'],
                'unique_together': {('project', 'week_number')},
            },
        ),
    ]
