# Generated by Django 6.0.4 on 2026-06-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stagaire', '0005_project_mentor_finalreport_weeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/'),
        ),
    ]
