# Generated by Django 6.0 on 2026-06-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stagaire', '0006_internshipreport_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipreport',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='gestion_stagaire.task'),
        ),
    ]
