# Generated by Django 6.0 on 2026-06-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stagaire', '0008_internshipreport_validated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_final_report',
            field=models.BooleanField(default=False, help_text='Marquer comme rapport final'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gestion_stagaire.project'),
        ),
    ]
